Base on new upstream
https://github.com/heroku/heroku-geo-buildpack/

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,139 +1,79 @@
-#!/usr/bin/env bash
-# bin/compile <build-dir> <cache-dir>
+#!/bin/bash
 
-# Fail fast
-set -e
+vendor_lib() {
+    LIBRARY=$1
+    VERSION=$2
+    VENDOR_DIR=$3
 
-# Debug
-# set -x
+    echo "-----> Installing $LIBRARY-$VERSION"
+    LIBRARY_URL="https://bucketeer-9aa8f376-a619-404c-b004-6db0317bcfe8.s3.amazonaws.com/$STACK/$LIBRARY/$LIBRARY-$VERSION.tar.gz"
 
-# Clean up leaking environment
-unset GIT_DIR
+    mkdir -p $VENDOR_DIR
+    if ! curl "${LIBRARY_URL}" -s | tar zxv -C $VENDOR_DIR &> /dev/null; then
+      echo " !     Requested $LIBRARY Version ($VERSION) is not available for this stack ($STACK)."
+      echo " !     Aborting."
+      exit 1
+    fi
 
-# Configuration
-S3_BUCKET=${HEROKU_GEO_BUILDBACK_S3_BUCKET:-"cyberdelia-geo-buildpack"}
-
-# Parameters
-if [ "${STACK}" = "scalingo" ] ; then
-  export STACK="cedar-14"
-fi
+    mkdir -p "$CACHE_DIR/.heroku-geo-buildpack/"
+    # Store library version for future reference
+    echo "$VERSION" > "$CACHE_DIR/.heroku-geo-buildpack/$LIBRARY-version"
+}
 
 BUILD_DIR=$1
-CACHE_DIR="${2}/${STACK}"
+CACHE_DIR=$2
+ENV_DIR=$3
+BP_DIR=$(cd "$(dirname "${0:-}")"; cd ..; pwd)
 
-# Setup profile file
-BP_DIR=$(cd $(dirname ${0:-}); cd ..; pwd)
-EXPORT_PATH="$BP_DIR/export"
-PROFILE_PATH="$BUILD_DIR/.profile.d/geo.sh"
+VENDOR_DIR="$BUILD_DIR/.heroku-geo-buildpack/vendor"
+
+DEFAULT_GDAL_VERSION="2.4.0"
+DEFAULT_GEOS_VERSION="3.7.2"
+DEFAULT_PROJ_VERSION="5.2.0"
+
+if [ -f "$ENV_DIR/GDAL_VERSION" ]; then
+    GDAL_VERSION=$(cat $ENV_DIR/GDAL_VERSION)
+elif [ -f "$CACHE_DIR/.heroku-geo-buildpack/GDAL-version" ]; then
+    GDAL_VERSION=$(cat $CACHE_DIR/.heroku-geo-buildpack/GDAL-version)
+else
+    GDAL_VERSION=$DEFAULT_GDAL_VERSION
+fi
+
+if [ -f "$ENV_DIR/GEOS_VERSION" ]; then
+    GEOS_VERSION=$(cat $ENV_DIR/GEOS_VERSION)
+elif [ -f "$CACHE_DIR/.heroku-geo-buildpack/GEOS-version" ]; then
+    GEOS_VERSION=$(cat $CACHE_DIR/.heroku-geo-buildpack/GEOS-version)
+else
+    GEOS_VERSION=$DEFAULT_GEOS_VERSION
+fi
+
+if [ -f "$ENV_DIR/PROJ_VERSION" ]; then
+    PROJ_VERSION=$(cat $ENV_DIR/PROJ_VERSION)
+elif [ -f "$CACHE_DIR/.heroku-geo-buildpack/PROJ-version" ]; then
+    PROJ_VERSION=$(cat $CACHE_DIR/.heroku-geo-buildpack/PROJ-version)
+else
+    PROJ_VERSION=$DEFAULT_PROJ_VERSION
+fi
+
+vendor_lib "GDAL" "$GDAL_VERSION" "$VENDOR_DIR"
+vendor_lib "GEOS" "$GEOS_VERSION" "$VENDOR_DIR"
+vendor_lib "PROJ" "$PROJ_VERSION" "$VENDOR_DIR"
+
+# Add some environment variables that are available to the next buildpacks, to ensure that pip can find the
+# GDAL installation as this is needed to pip install GDAL
+echo "export PATH=\"$BUILD_DIR/.heroku-geo-buildpack/vendor/bin:\$PATH\"" >> "$BP_DIR/export"
+echo "export LIBRARY_PATH=\"$BUILD_DIR/.heroku-geo-buildpack/vendor/lib:\$LIBRARY_PATH\"" >> "$BP_DIR/export"
+echo "export LD_LIBRARY_PATH=\"$BUILD_DIR/.heroku-geo-buildpack/vendor/lib:\$LD_LIBRARY_PATH\"" >> "$BP_DIR/export"
+echo "export CPLUS_INCLUDE_PATH=\"$BUILD_DIR/.heroku-geo-buildpack/vendor/include:\$CPLUS_INCLUDE_PATH\"" >> "$BP_DIR/export"
+echo "export C_INCLUDE_PATH=\"$BUILD_DIR/.heroku-geo-buildpack/vendor/include:\$C_INCLUDE_PATH\"" >> "$BP_DIR/export"
+
+PROFILE_PATH="$BUILD_DIR/.profile.d/heroku-geo-buildpack.sh"
 mkdir -p $(dirname $PROFILE_PATH)
 
-# Functions
-function indent() {
-  c='s/^/       /'
-  case $(uname) in
-    Darwin) sed -l "$c";;
-    *)      sed -u "$c";;
-  esac
-}
-
-function manifest_version() {
-  curl "http://${S3_BUCKET}.s3.amazonaws.com/${STACK}/manifest.${1}" -s -o - | head -n 1
-}
-
-function download_package() {
-  name="$1"
-  version="$2"
-  location="$3"
-
-  mkdir -p $location
-  package="https://${S3_BUCKET}.s3.amazonaws.com/${STACK}/$name-$version.tgz"
-  curl $package -s -o - | tar xzf - -C $location
-}
-
-function set-export(){
-  echo "export $1=$2" >> $EXPORT_PATH
-}
-
-function set-env (){
-  set-export "$1" "$3"
-  echo "export $1=$2" >> $PROFILE_PATH
-}
-
-function set-default-env (){
-  set-export "$1" "$3"
-  echo "export $1=\${$1:-$2}" >> $PROFILE_PATH
-}
-
-# Retrieve versions
-GEOS_VERSION=$(manifest_version "geos")
-GDAL_VERSION=$(manifest_version "gdal")
-PROJ_VERSION=$(manifest_version "proj")
-
-# Display some information
-echo "Using geos version: ${GEOS_VERSION}" | indent
-echo "Using gdal version: ${GDAL_VERSION}" | indent
-echo "Using proj version: ${PROJ_VERSION}" | indent
-
-# Vendor directories
-VENDORED_GEOS="vendor/geos/$GEOS_VERSION"
-VENDORED_GDAL="vendor/gdal/$GDAL_VERSION"
-VENDORED_PROJ="vendor/proj/$PROJ_VERSION"
-
-# Make sure cache dir exists
-mkdir -p $CACHE_DIR
-
-if [ ! -d $CACHE_DIR/$VENDORED_GEOS ]; then
-  echo "-----> Fetching and vendoring geos"
-  rm -rf "$CACHE_DIR/vendor/geos"
-  download_package "geos" "${GEOS_VERSION}" "${CACHE_DIR}/${VENDORED_GEOS}"
-fi
-
-if [ ! -d $CACHE_DIR/$VENDORED_GDAL ]; then
-  echo "-----> Fetching and vendoring gdal"
-  rm -rf "$CACHE_DIR/vendor/gdal"
-  download_package "gdal" "${GDAL_VERSION}" "${CACHE_DIR}/${VENDORED_GDAL}"
-fi
-
-if [ ! -d $CACHE_DIR/$VENDORED_PROJ ]; then
-  echo "-----> Fetching and vendoring proj"
-  rm -rf "$CACHE_DIR/vendor/proj"
-  download_package "proj" "${PROJ_VERSION}" "${CACHE_DIR}/${VENDORED_PROJ}"
-fi
-
-TARGET_VENDOR_DIR=".scalingo/vendor"
-# Copy artifacts out of cache if exists.
-for dir in $VENDORED_GEOS $VENDORED_GDAL $VENDORED_PROJ; do
-  mkdir -p $BUILD_DIR/$TARGET_VENDOR_DIR
-  cp -r $CACHE_DIR/$dir/* $BUILD_DIR/$TARGET_VENDOR_DIR &> /dev/null || true
-done
-
-# App directories
-APP_VENDOR="/app/$TARGET_VENDOR_DIR"
-BUILD_VENDOR="$BUILD_DIR/$TARGET_VENDOR_DIR"
-
-# Setup environment variables
-set-env GEOS_LIBRARY_PATH "$APP_VENDOR/lib" "$BUILD_VENDOR/lib"
-set-env GDAL_LIBRARY_PATH "$APP_VENDOR/lib" "$BUILD_VENDOR/lib"
-set-env PROJ4_LIBRARY_PATH "$APP_VENDOR/lib" "$BUILD_VENDOR/lib"
-set-env GDAL_DATA "$APP_VENDOR/share/gdal" "$BUILD_VENDOR/share/gdal"
-
-# Bundle workaround
-mkdir -p $BUILD_DIR/.bundle
-if [ -f $CACHE_DIR/.bundle/config ]; then
-  rm $CACHE_DIR/.bundle/config
-fi
-echo "---
-BUNDLE_BUILD__RGEO: "--with-geos-dir=$BUILD_DIR/$TARGET_VENDOR_DIR --with-geos-lib=$BUILD_DIR/$TARGET_VENDOR_DIR/lib --with-proj-dir=$BUILD_DIR/$TARGET_VENDOR_DIR --with-proj-lib=$BUILD_DIR/$TARGET_VENDOR_DIR/lib"
-BUNDLE_FROZEN: '1'
-BUNDLE_PATH: vendor/bundle
-BUNDLE_BIN: vendor/bundle/bin
-BUNDLE_WITHOUT: development:test
-BUNDLE_DISABLE_SHARED_GEMS: '1'
-" > $BUILD_DIR/.bundle/config
-
-set-default-env LIBRARY_PATH "$APP_VENDOR/lib" "$BUILD_VENDOR/lib"
-set-default-env LD_LIBRARY_PATH "$APP_VENDOR/lib" "$BUILD_VENDOR/lib"
-set-default-env CPATH "$APP_VENDOR/include" "$BUILD_VENDOR/include"
-
-echo "-----> Vendoring geo libraries done"
-
+# Export vars
+echo 'export GDAL_LIBRARY_PATH="$HOME/.heroku-geo-buildpack/vendor/lib/libgdal.so"' >> $PROFILE_PATH
+echo 'export GEOS_LIBRARY_PATH="$HOME/.heroku-geo-buildpack/vendor/lib/libgeos_c.so"' >> $PROFILE_PATH
+echo 'export PROJ4_LIBRARY_PATH="$HOME/.heroku-geo-buildpack/vendor/lib/libproj.so"' >> $PROFILE_PATH
+echo 'export GDAL_DATA="$HOME/.heroku-geo-buildpack/vendor/share/gdal"' >> $PROFILE_PATH
+echo 'export PATH="$HOME/.heroku-geo-buildpack/vendor/bin:$PATH"' >> $PROFILE_PATH
+echo 'export LD_LIBRARY_PATH="$HOME/.heroku-geo-buildpack/vendor/lib:$LD_LIBRARY_PATH"' >> $PROFILE_PATH
